In [2]:
import re

In [163]:
x = '100x^30-50x^1-5987x^0'
x

'100x^30-50x^1-5987x^0'

In [164]:
x = x.lower()
x = x.replace(' ','')
if x[0] != '-':
    x = '+' + x
x

'+100x^30-50x^1-5987x^0'

In [165]:
x = re.findall(r'([+-]?\d*)x\^(\d+)',x)
x

[('+100', '30'), ('-50', '1'), ('-5987', '0')]

In [167]:
for term in x:
    print(term[0])
    print(term[1])

+100
30
-50
1
-5987
0


In [154]:
# get the coffecients and orders
coffecients = []
orders = []
x = re.findall(r'([+-]?\d*x\^\d+)',x)
x

['+100x^30', '-50x^1', '-5987x^0']

In [157]:
for term in x:
    print(re.findall(r'([+-]?\d*)x\^(\d+)',term))

[('+100', '30')]
[('-50', '1')]
[('-5987', '0')]


In [141]:

coeffs = []
orders = []
temp = ''
for i,c in enumerate(x):
    temp += c
    if c == 'x':
        print(temp[:-1])
        temp = ''

+100
^30-50


In [129]:
int('-5') + int('10')

5

In [89]:
x.split()

['5x^2', '+2x', '+1']

In [83]:
result = re.findall("x^", x)
result

[]

In [42]:
x = '+' + x

In [43]:
x

'+5x^2+2x-3'

In [48]:
x

'+5x^2+2x-3'

In [54]:

coeffs = []
orders = []
for i,ch in enumerate(x):
    if ch == 'x':
        print(x[i-2:i])
        if x[i+1] == '^':
            print(x[i+2])
        else:
            print('1')

+5
2
+2
1


In [10]:
for term in x:
    print(term.split(x))

5x^2
2x
3


In [172]:
sorted(zip([1,2,3],[6,5,4]),key=lambda x: x[1],reverse=True)

[(1, 6), (2, 5), (3, 4)]

In [2]:
import numpy as np

In [15]:
a = np.array([5,2,5])
b = np.array([3,-5,10])

In [18]:
a = a.reshape(1,-1)
b = b.reshape(1,-1)
print(a.shape,b.shape)

(1, 3) (1, 3)


In [24]:
np.add.outer(a,b)

array([[[[ 8,  0, 15]],

        [[ 5, -3, 12]],

        [[ 8,  0, 15]]]])

In [25]:
np.outer(b,a)

array([[ 15,   6,  15],
       [-25, -10, -25],
       [ 50,  20,  50]])

In [20]:
np.matmul(b.T,a)

array([[ 15,   6,  15],
       [-25, -10, -25],
       [ 50,  20,  50]])

In [26]:
a = np.array([2,1,0])
b = np.array([3,2,0])

In [31]:
z = np.add.outer(b,a)
z

array([[5, 4, 3],
       [4, 3, 2],
       [2, 1, 0]])

In [36]:
z[0,:]

array([5, 4, 3])